const D={
profile:{name:"Sai Prashant",email:"sai@example.com",designation:"Solution Architect",practice:"Data & AI",location:"India"},
projects:[
{id:"PRJ-001",name:"Regions Bank",client:"Regions Bank",deal:"Ongoing",status:"Active",start:"2026-07-15",end:"2026-10-31",pillars:["Proposal & RFP Excellence","Sales Enablement & GTM Support"],url:""},
{id:"PRJ-002",name:"Godrej Capital",client:"Godrej Capital",deal:"Ongoing",status:"Active",start:"2026-08-01",end:"2026-10-15",pillars:["Proposal & RFP Excellence"],url:""},
{id:"PRJ-003",name:"Deloitte Data Support",client:"Deloitte",deal:"Completed",status:"Completed",start:"2026-01-05",end:"2026-06-30",pillars:["Sales Enablement & GTM Support"],url:""}],
versions:[
{id:"VER-001",projectId:"PRJ-001",number:"V1",name:"Initial Proposal",reason:"New project approach",status:"Superseded",date:"2026-07-18",url:""},
{id:"VER-002",projectId:"PRJ-001",number:"V2",name:"Revised Approach",reason:"Client feedback",status:"Superseded",date:"2026-07-30",url:""},
{id:"VER-003",projectId:"PRJ-001",number:"V3",name:"Revised / Rejected",reason:"Client rejection",status:"Rejected",date:"2026-08-12",url:""},
{id:"VER-004",projectId:"PRJ-001",number:"V4",name:"Rebuilt Approach",reason:"Major scope change",status:"In Progress",date:"2026-08-20",url:""},
{id:"VER-005",projectId:"PRJ-002",number:"V1",name:"Modernization Proposal",reason:"New project approach",status:"Submitted",date:"2026-08-05",url:""}],
activities:[
{id:"ACT-001",projectId:"PRJ-001",versionId:"VER-004",date:"2026-09-09",category:"Architecture",title:"Refined solution architecture",details:"Refined the end-to-end architecture and clarified processing boundaries.",status:"Completed",hours:2.5,tags:["Azure","Architecture"]},
{id:"ACT-002",projectId:"PRJ-001",versionId:"VER-004",date:"2026-09-08",category:"AI / GenAI",title:"Defined AI capabilities",details:"Defined AI and GenAI capabilities for the proposal.",status:"Completed",hours:1.5,tags:["AI","GenAI"]},
{id:"ACT-003",projectId:"PRJ-001",versionId:"VER-004",date:"2026-09-07",category:"Agentic AI",title:"Defined Agentic AI approach",details:"Outlined agentic capabilities and target use cases.",status:"Completed",hours:2,tags:["Agentic AI"]},
{id:"ACT-004",projectId:"PRJ-001",versionId:"VER-004",date:"2026-09-05",category:"Presentation / Demo",title:"Prepared client presentation",details:"Prepared and refined client-facing presentation material.",status:"Completed",hours:3,tags:["Presentation"]},
{id:"ACT-005",projectId:"PRJ-001",versionId:"VER-004",date:"2026-09-03",category:"Solutioning",title:"Separated Power BI capability",details:"Separated the Power BI capability and clarified responsibilities.",status:"Completed",hours:1.5,tags:["Power BI"]},
{id:"ACT-006",projectId:"PRJ-002",versionId:"VER-005",date:"2026-09-02",category:"Proposal / RFP",title:"Reviewed proposal response",details:"Reviewed and refined response content.",status:"Completed",hours:2,tags:["RFP","Data"]},
{id:"ACT-007",projectId:"PRJ-003",versionId:null,date:"2026-08-29",category:"Client Delivery",title:"Closed data support actions",details:"Completed outstanding support actions and documentation.",status:"Completed",hours:2,tags:["Data"]}],
categories:["Client Delivery","Client Meeting / Discussion","Workshop","Presentation / Demo","Requirement Analysis","Solution Design","Architecture","Proposal / RFP","Solutioning","Estimation / Effort Analysis","Proposal Review","Sales / GTM Support","Collateral / Reusable Asset","AI / GenAI","Agentic AI","Data & Analytics","Architecture / Technology Research","POC / Prototype","Innovation","Internal Initiative","Knowledge Sharing","Mentoring / Coaching","Team / Practice Contribution","Process Improvement","Learning / Training","Certification","Skill Development","Documentation","Technical Documentation","Reusable Asset Creation"],
pillars:["Collateral Development & Reusable Asset Creation","Proposal & RFP Excellence","Market Intelligence & Trend Analysis","Sales Enablement & GTM Support","Self Improvement & Skill Enhancement"],
dealStatuses:["Won","Completed","Lost","Ongoing"],projectStatuses:["Active","Completed","On Hold","Cancelled"],
versionStatuses:["Baseline","In Progress","Submitted","Under Review","Approved","Rejected","Superseded","Final"]
};
const S={page:"dashboard",project:null,openVersions:new Set(["V4"]),filter:{search:"",project:"all",category:"all",status:"all",from:"",to:""}};
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const proj=id=>D.projects.find(x=>x.id===id), ver=id=>D.versions.find(x=>x.id===id);
const date=x=>x?new Date(x+"T00:00:00").toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"—";
const hrs=a=>a.reduce((s,x)=>s+Number(x.hours||0),0);
function badge(x){let c=["Completed","Approved","Won","Final","Active"].includes(x)?"ok":["In Progress","Ongoing","Submitted","Under Review","Baseline"].includes(x)?"blue":["Rejected","Lost","Cancelled"].includes(x)?"bad":["Superseded","On Hold"].includes(x)?"warn":"gray";return `<span class="badge ${c}">${esc(x)}</span>`}
function toast(x){let t=document.getElementById("toast");t.textContent=x;t.className="show";setTimeout(()=>t.className="",1800)}
function shell(){let nav=[["dashboard","▦","Dashboard"],["activities","☷","Activities"],["projects","▣","Projects"],["reports","▤","Reports"],["settings","⚙","Settings"],["profile","◉","Profile"]];return `<div class="shell"><aside class="side"><div class="brand">WORK ACTIVITY<br>TRACKER<small>Personal work & appraisal</small></div><nav class="nav">${nav.map(n=>`<button class="${S.page===n[0]?"active":""}" data-nav="${n[0]}">${n[1]} &nbsp; ${n[2]}</button>`).join("")}</nav><div class="side-foot">${esc(D.profile.name)}<br><span>${esc(D.profile.designation)}</span></div></aside><main class="main"><header class="top"><div><strong>${nav.find(n=>n[0]===S.page)?.[2]||"Project"}</strong><small>Work Activity Tracker</small></div><div class="actions"><button class="btn primary" data-act="add">＋ Add Activity</button></div></header><div class="content" id="content"></div></main></div>`}
function render(){document.getElementById("app").innerHTML=shell();let c=document.getElementById("content");c.innerHTML=S.page==="dashboard"?dashboard():S.page==="activities"?activities():S.page==="projects"?(S.project?detail():projects()):S.page==="reports"?reports():S.page==="settings"?settings():profile();bind()}
function table(rows,actions=true){if(!rows.length)return `<div class="empty">No activities found.</div>`;return `<div style="overflow:auto"><table><thead><tr><th>Date</th><th>Project</th><th>Version</th><th>Category</th><th>Activity</th><th>Status</th><th>Hours</th>${actions?"<th></th>":""}</tr></thead><tbody>${rows.map(a=>{let p=proj(a.projectId),v=ver(a.versionId);return `<tr><td>${date(a.date)}</td><td><b>${esc(p?.name||"—")}</b><span class="muted">${esc(p?.client||"")}</span></td><td>${v?badge(v.number):"—"}</td><td>${esc(a.category)}</td><td><b>${esc(a.title)}</b><span class="muted">${esc(a.details)}</span></td><td>${badge(a.status)}</td><td>${Number(a.hours||0).toFixed(1)}</td>${actions?`<td><button class="btn" data-act="edit" data-id="${a.id}">Edit</button> <button class="btn danger" data-act="del" data-id="${a.id}">Delete</button></td>`:""}</tr>`}).join("")}</tbody></table></div>`}
function dashboard(){let cats={};D.activities.forEach(a=>cats[a.category]=(cats[a.category]||0)+1);let top=Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,5),max=Math.max(...top.map(x=>x[1]),1),days=["03","04","05","06","07","08","09"],counts=days.map(d=>D.activities.filter(a=>a.date.endsWith("-"+d)).length),mx=Math.max(...counts,1);return `<div class="head"><div><h1>Good morning, ${esc(D.profile.name.split(" ")[0])}</h1><p>Snapshot of your work activity and appraisal evidence.</p></div><div class="actions"><button class="btn" data-nav="reports">Reports</button><button class="btn primary" data-act="add">＋ Add Activity</button></div></div><div class="cards"><div class="card kpi"><label>ACTIVITIES</label><b>${D.activities.length}</b><span>Recorded work items</span></div><div class="card kpi"><label>PROJECTS WORKED ON</label><b>${new Set(D.activities.map(a=>a.projectId)).size}</b><span>Across portfolio</span></div><div class="card kpi"><label>VERSIONS CREATED</label><b>${D.versions.length}</b><span>Major deliverable states</span></div><div class="card kpi"><label>HOURS LOGGED</label><b>${hrs(D.activities).toFixed(1)}</b><span>Recorded effort</span></div></div><div class="grid2"><div class="card"><div class="cardhead"><b>Activity Trend</b><span class="muted">Recent activity count</span></div><div class="cardbody"><div class="bars">${days.map((d,i)=>`<div class="barcol"><small>${counts[i]}</small><div class="bar" style="height:${Math.max(7,counts[i]/mx*145)}px"></div><small>${d} Sep</small></div>`).join("")}</div></div></div><div class="card"><div class="cardhead"><b>Work by Category</b></div><div class="cardbody"><div class="donutrow"><div class="donut"></div><div class="legend">${top.map(x=>`<div><i class="dot" style="background:#6d9ee8"></i><span>${esc(x[0])} <b>${x[1]}</b></span></div>`).join("")}</div></div></div></div></div><div class="card tablecard" style="margin-top:16px"><div class="cardhead"><b>Recent Activity</b><button class="btn" data-nav="activities">View all</button></div>${table(D.activities.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5),false)}</div>`}
function activities(){let f=S.filter,r=D.activities.filter(a=>{let p=proj(a.projectId);return(!f.search||[a.title,a.details,a.category,p?.name,p?.client].join(" ").toLowerCase().includes(f.search.toLowerCase()))&&(f.project==="all"||a.projectId===f.project)&&(f.category==="all"||a.category===f.category)&&(f.status==="all"||a.status===f.status)&&(!f.from||a.date>=f.from)&&(!f.to||a.date<=f.to)}).sort((a,b)=>b.date.localeCompare(a.date));return `<div class="head"><div><h1>Activities</h1><p>Record work personally performed against projects and versions.</p></div><button class="btn primary" data-act="add">＋ Add Activity</button></div><div class="card tablecard"><div class="toolbar"><input class="input search" id="search" placeholder="Search activity, project, category..." value="${esc(f.search)}"><select class="select" id="filterProject"><option value="all">All Projects</option>${D.projects.map(p=>`<option value="${p.id}" ${f.project===p.id?"selected":""}>${esc(p.name)}</option>`).join("")}</select><select class="select" id="filterCat"><option value="all">All Categories</option>${D.categories.map(x=>`<option ${f.category===x?"selected":""}>${esc(x)}</option>`).join("")}</select><select class="select" id="filterStatus"><option value="all">All Statuses</option>${["Completed","In Progress","Blocked"].map(x=>`<option ${f.status===x?"selected":""}>${x}</option>`).join("")}</select><input class="input" type="date" id="from" value="${f.from}"><input class="input" type="date" id="to" value="${f.to}"></div>${table(r,true)}</div>`}
function projects(){return `<div class="head"><div><h1>Projects</h1><p>Manage client work and its version history.</p></div><button class="btn primary" data-act="projectAdd">＋ Add Project</button></div><div class="projectgrid">${D.projects.map(p=>`<div class="card project" data-project="${p.id}"><div style="display:flex;justify-content:space-between"><div><h3>${esc(p.name)}</h3><p>${esc(p.client)}</p></div>${badge(p.status)}</div><div class="projecttags">${badge(p.deal)}${p.pillars.slice(0,1).map(x=>`<span class="badge gray">${esc(x)}</span>`).join("")}</div><div class="stats"><div><small>Versions</small><b>${D.versions.filter(v=>v.projectId===p.id).length}</b></div><div><small>Activities</small><b>${D.activities.filter(a=>a.projectId===p.id).length}</b></div><div><small>Hours</small><b>${hrs(D.activities.filter(a=>a.projectId===p.id)).toFixed(1)}</b></div></div></div>`).join("")}</div>`}
function detail(){let p=proj(S.project),vs=D.versions.filter(v=>v.projectId===p.id).sort((a,b)=>b.date.localeCompare(a.date));return `<div class="head"><div><button class="btn" data-act="back">← Projects</button></div><div class="actions"><button class="btn" data-act="projectEdit" data-id="${p.id}">Edit Project</button><button class="btn primary" data-act="versionAdd" data-id="${p.id}">＋ Add Version</button></div></div><div class="card detail"><div style="display:flex;justify-content:space-between;gap:15px"><div><h1>${esc(p.name)}</h1><p style="color:var(--muted)">${esc(p.client)}</p><div class="projecttags">${badge(p.deal)}${badge(p.status)}${p.pillars.map(x=>`<span class="badge gray">${esc(x)}</span>`).join("")}</div></div></div><div class="info"><div><small>Start Date</small><b>${date(p.start)}</b></div><div><small>Target End</small><b>${date(p.end)}</b></div><div><small>Versions</small><b>${vs.length}</b></div><div><small>Activities</small><b>${D.activities.filter(a=>a.projectId===p.id).length}</b></div></div></div><div class="card"><div class="cardhead"><b>Versions & Activities</b><span class="muted">Major deliverable states</span></div><div class="cardbody">${vs.map(v=>{let open=S.openVersions.has(v.number),a=D.activities.filter(x=>x.versionId===v.id);return `<div class="version"><div class="vhead" data-vtoggle="${v.number}"><span>${open?"▾":"▸"}</span><span class="vnum">${esc(v.number)}</span><div><b>${esc(v.name)}</b><span class="muted">${esc(v.reason)} · ${date(v.date)}</span></div><span style="margin-left:auto">${badge(v.status)}</span></div>${open?`<div class="vbody">${table(a,true)}<button class="btn primary" data-act="versionActivity" data-id="${v.id}">＋ Add Activity</button></div>`:""}</div>`}).join("")}</div></div>`}
function reports(){let r=D.activities.filter(a=>(!S.filter.from||a.date>=S.filter.from)&&(!S.filter.to||a.date<=S.filter.to));return `<div class="head"><div><h1>Reports</h1><p>Appraisal-ready summary for a selected activity period.</p></div><div class="actions"><button class="btn" data-act="csv">↓ CSV</button><button class="btn primary" data-act="print">Print / PDF</button></div></div><div class="card toolbar"><b style="padding:9px 2px">Activity date range</b><input class="input" type="date" id="rfrom" value="${S.filter.from}"><span style="padding:9px;color:var(--muted)">to</span><input class="input" type="date" id="rto" value="${S.filter.to}"><button class="btn" id="applyReport">Apply</button></div><div class="cards" style="margin-top:15px"><div class="card kpi"><label>ACTIVITIES</label><b>${r.length}</b></div><div class="card kpi"><label>PROJECTS</label><b>${new Set(r.map(a=>a.projectId)).size}</b></div><div class="card kpi"><label>HOURS</label><b>${hrs(r).toFixed(1)}</b></div><div class="card kpi"><label>VERSIONS</label><b>${new Set(r.map(a=>a.versionId).filter(Boolean)).size}</b></div></div><div class="card tablecard">${table(r,true)}</div>`}
function settings(){let master=(title,items,key)=>`<div class="card"><div class="cardhead"><b>${title}</b><button class="btn primary" data-masteradd="${key}">＋ Add</button></div><div class="setting">${items.map((x,i)=>`<div class="settingrow"><span>${esc(x.name||x)}</span><button class="btn" data-masteredit="${key}:${i}">Edit</button></div>`).join("")}</div></div>`;return `<div class="head"><div><h1>Settings</h1><p>Configure master values used in the tracker.</p></div></div><div class="settings">${master("Activity Categories",D.categories.slice(0,12),"categories")}${master("Pillars",D.pillars,"pillars")}${master("Deal Status",D.dealStatuses,"dealStatuses")}${master("Project Status",D.projectStatuses,"projectStatuses")}${master("Version Status",D.versionStatuses,"versionStatuses")}</div>`}
function profile(){let p=D.profile;return `<div class="head"><div><h1>Profile</h1><p>Personal information used in reports.</p></div><button class="btn primary" data-act="profileEdit">Edit Profile</button></div><div class="card detail"><h2>${esc(p.name)}</h2><p>${esc(p.designation)} · ${esc(p.practice)}</p><div class="info" style="grid-template-columns:repeat(2,1fr)">${Object.entries(p).map(([k,v])=>`<div><small>${esc(k)}</small><b>${esc(v||"—")}</b></div>`).join("")}</div></div>`}
function formActivity(a={}){return `<div class="formgrid"><div class="field"><label>Date *</label><input class="input" id="fdate" type="date" value="${a.date||new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Project *</label><select class="select" id="fproject"><option value="">Select</option>${D.projects.map(p=>`<option value="${p.id}" ${a.projectId===p.id?"selected":""}>${esc(p.name)}</option>`).join("")}</select></div><div class="field"><label>Version</label><select class="select" id="fversion"><option value="">No version</option>${D.versions.filter(v=>!a.projectId||v.projectId===a.projectId).map(v=>`<option value="${v.id}" ${a.versionId===v.id?"selected":""}>${v.number} — ${esc(v.name)}</option>`).join("")}</select></div><div class="field"><label>Category *</label><select class="select" id="fcat"><option value="">Select</option>${D.categories.map(x=>`<option ${a.category===x?"selected":""}>${esc(x)}</option>`).join("")}</select></div><div class="field full"><label>Activity Title *</label><input class="input" id="ftitle" value="${esc(a.title||"")}" placeholder="What did you work on?"></div><div class="field full"><label>Details / Outcome</label><textarea class="area" id="fdetails">${esc(a.details||"")}</textarea></div><div class="field"><label>Status</label><select class="select" id="fstatus">${["Completed","In Progress","Blocked"].map(x=>`<option ${a.status===x?"selected":""}>${x}</option>`).join("")}</select></div><div class="field"><label>Hours</label><input class="input" id="fhours" type="number" step=".5" min="0" value="${a.hours??""}"></div><div class="field full"><label>URL</label><input class="input" id="furl" value="${esc(a.url||"")}" placeholder="SharePoint / Teams / GitHub / internal URL"></div><div class="field full"><label>Tags</label><input class="input" id="ftags" value="${esc((a.tags||[]).join(", "))}" placeholder="Azure, Power BI, AI"></div></div>`}
function modal(title,body,save){document.getElementById("modal").innerHTML=`<div class="modalbg"><div class="drawer"><div class="dhead"><h2>${title}</h2><button class="btn" id="close">×</button></div><div class="dbody">${body}</div><div class="dfoot"><button class="btn" id="cancel">Cancel</button><button class="btn primary" id="save">${save||"Save"}</button></div></div></div>`;document.getElementById("close").onclick=close;document.getElementById("cancel").onclick=close}
function close(){document.getElementById("modal").innerHTML=""}
function val(id){return document.getElementById(id)?.value||""}
function openActivity(a=null,preset=null){let x=a||{projectId:preset?ver(preset)?.projectId:null,versionId:preset,status:"Completed"};modal(a?"Edit Activity":"Add Activity",formActivity(x));document.getElementById("save").onclick=()=>{let o={date:val("fdate"),projectId:val("fproject"),versionId:val("fversion")||null,category:val("fcat"),title:val("ftitle"),details:val("fdetails"),status:val("fstatus"),hours:Number(val("fhours")||0),url:val("furl"),tags:val("ftags").split(",").map(x=>x.trim()).filter(Boolean)};if(!o.date||!o.projectId||!o.category||!o.title)return toast("Complete required fields.");if(a)Object.assign(a,o);else D.activities.unshift({id:"ACT-"+String(Date.now()),...o});close();render();toast(a?"Activity updated":"Activity added")};document.getElementById("fproject").onchange=()=>{let p=val("fproject"),s=document.getElementById("fversion");s.innerHTML='<option value="">No version</option>'+D.versions.filter(v=>v.projectId===p).map(v=>`<option value="${v.id}">${v.number} — ${esc(v.name)}</option>`).join("")}}
function openProject(p=null){let x=p||{};modal(p?"Edit Project":"Add Project",`<div class="formgrid"><div class="field"><label>Project Name *</label><input class="input" id="pn" value="${esc(x.name||"")}"></div><div class="field"><label>Client / Account *</label><input class="input" id="pc" value="${esc(x.client||"")}"></div><div class="field"><label>Deal Status</label><select class="select" id="pd">${D.dealStatuses.map(s=>`<option ${x.deal===s?"selected":""}>${s}</option>`).join("")}</select></div><div class="field"><label>Project Status</label><select class="select" id="ps">${D.projectStatuses.map(s=>`<option ${x.status===s?"selected":""}>${s}</option>`).join("")}</select></div><div class="field"><label>Start Date</label><input class="input" id="pst" type="date" value="${x.start||""}"></div><div class="field"><label>Target End Date</label><input class="input" id="pe" type="date" value="${x.end||""}"></div><div class="field full"><label>Project URL</label><input class="input" id="pu" value="${esc(x.url||"")}"></div></div>`,"Save Project");document.getElementById("save").onclick=()=>{let o={name:val("pn"),client:val("pc"),deal:val("pd"),status:val("ps"),start:val("pst"),end:val("pe"),url:val("pu"),pillars:x.pillars||[]};if(!o.name||!o.client)return toast("Complete required fields.");if(p)Object.assign(p,o);else D.projects.push({id:"PRJ-"+Date.now(),...o});close();render();toast("Project saved")}}
function openVersion(existing=null,pid=null){let p=pid||existing?.projectId||S.project,n=Math.max(0,...D.versions.filter(v=>v.projectId===p).map(v=>parseInt(v.number.slice(1))||0))+1,x=existing||{projectId:p,number:"V"+n,status:"In Progress",date:new Date().toISOString().slice(0,10)};modal(existing?"Edit Version":"Add Version",`<div class="formgrid"><div class="field"><label>Project</label><select class="select" id="vp">${D.projects.map(p=>`<option value="${p.id}" ${x.projectId===p.id?"selected":""}>${esc(p.name)}</option>`).join("")}</select></div><div class="field"><label>Version Number</label><input class="input" id="vn" value="${x.number}"></div><div class="field full"><label>Version Name *</label><input class="input" id="vname" value="${esc(x.name||"")}"></div><div class="field"><label>Reason</label><select class="select" id="vr">${["New project approach","Client feedback","Client rejection","Major scope change","Internal refinement","Final version","Other"].map(s=>`<option ${x.reason===s?"selected":""}>${s}</option>`).join("")}</select></div><div class="field"><label>Status</label><select class="select" id="vs">${D.versionStatuses.map(s=>`<option ${x.status===s?"selected":""}>${s}</option>`).join("")}</select></div><div class="field"><label>Created Date</label><input class="input" id="vd" type="date" value="${x.date}"></div><div class="field"><label>Version URL</label><input class="input" id="vu" value="${esc(x.url||"")}"></div></div>`,"Save Version");document.getElementById("save").onclick=()=>{let o={projectId:val("vp"),number:val("vn"),name:val("vname"),reason:val("vr"),status:val("vs"),date:val("vd"),url:val("vu")};if(!o.name)return toast("Version name is required.");if(existing)Object.assign(existing,o);else D.versions.push({id:"VER-"+Date.now(),...o});close();S.project=o.projectId;render();toast("Version saved")}}
function csv(){let r=[["Activity ID","Date","Project","Version","Category","Title","Details","Status","Hours","URL","Tags"]];D.activities.forEach(a=>r.push([a.id,a.date,proj(a.projectId)?.name||"",ver(a.versionId)?.number||"",a.category,a.title,a.details,a.status,a.hours,a.url||"",a.tags.join("; ")]));let s=r.map(x=>x.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\n"),u=URL.createObjectURL(new Blob([s],{type:"text/csv"})),a=document.createElement("a");a.href=u;a.download="work-activity-tracker.csv";a.click();URL.revokeObjectURL(u)}
function bind(){document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>{S.page=b.dataset.nav;S.project=null;render()});document.querySelectorAll("[data-project]").forEach(b=>b.onclick=()=>{S.project=b.dataset.project;render()});document.querySelectorAll("[data-vtoggle]").forEach(b=>b.onclick=()=>{let n=b.dataset.vtoggle;S.openVersions.has(n)?S.openVersions.delete(n):S.openVersions.add(n);render()});document.querySelectorAll("[data-act]").forEach(b=>b.onclick=()=>{let a=b.dataset.act,id=b.dataset.id;if(a==="add")openActivity();if(a==="edit")openActivity(D.activities.find(x=>x.id===id));if(a==="del"&&confirm("Delete this activity?")){D.activities=D.activities.filter(x=>x.id!==id);render();toast("Activity deleted")};if(a==="projectAdd")openProject();if(a==="projectEdit")openProject(proj(id));if(a==="back"){S.project=null;render()};if(a==="versionAdd")openVersion(null,id);if(a==="versionActivity")openActivity(null,id);if(a==="csv")csv();if(a==="print")window.print();if(a==="profileEdit")toast("Profile editing can be connected next")});document.getElementById("search")?.addEventListener("input",e=>{S.filter.search=e.target.value;render()});["filterProject","filterCat","filterStatus","from","to"].forEach(id=>document.getElementById(id)?.addEventListener("change",e=>{let m={filterProject:"project",filterCat:"category",filterStatus:"status",from:"from",to:"to"};S.filter[m[id]]=e.target.value;render()}));document.getElementById("applyReport")?.addEventListener("click",()=>{S.filter.from=val("rfrom");S.filter.to=val("rto");render()});document.querySelectorAll("[data-masteradd]").forEach(b=>b.onclick=()=>{let x=prompt("New value:");if(x){let k=b.dataset.masteradd;D[k].push(x);render();toast("Added")}});document.querySelectorAll("[data-masteredit]").forEach(b=>b.onclick=()=>{let [k,i]=b.dataset.masteredit.split(":");let old=D[k][i].name||D[k][i],x=prompt("Edit value:",old);if(x){if(typeof D[k][i]==="string")D[k][i]=x;else D[k][i].name=x;render();toast("Updated")}})}
render();
